sudo: required
os: linux
dist: trusty
services:
  - docker
env:
  matrix:
    - proxy=default build_args="--use-zlog"
    - proxy=no_zlog build_args=""
language: generic
dotnet: 1.0.0-preview2-003121
install: "./bld/travis_install.sh"
script: "./bld/build.sh -c $build_args"
