sudo: required
os: linux
dist: trusty
services:
  - docker
env:
  matrix:
    - proxy=default_release build_args="-C Release --skip-unittests --use-zlog"
    - proxy=no_zlog_release build_args="-C Release --skip-unittests"
    - proxy=default_debug build_args="-C Debug --use-zlog"
    - proxy=no_zlog_debug build_args="-C Debug"
language: c
compiler: 
  - gcc
  - clang
script: "bash bld/build.sh -c $build_args"
