environment:
  matrix:
    - proxy: default
      build_args: --use-zlog
    - proxy: default_x64
      build_args: -p x64 --use-zlog
    - proxy: no_zlog 
      build_args: --skip-dotnet 
    - proxy: no_zlog_x64
      build_args: -p x64 --skip-dotnet 
    - proxy: with_openssl
      build_args: --skip-dotnet --use-openssl
    - proxy: with_openssl_x64
      build_args: -p x64 --skip-dotnet --use-openssl
    - proxy: with_libwebsockets
      build_args: --skip-dotnet --use-libwebsockets
    - proxy: with_libwebsockets_x64
      build_args: -p x64 --skip-dotnet --use-libwebsockets
image: Visual Studio 2015
install:
  - appveyor DownloadFile https://libwebsockets.org:444/Win32OpenSSL-1_0_2h.exe
  - Win32OpenSSL-1_0_2h.exe /silent /verysilent /sp- /suppressmsgboxes
build:
build_script:
  - call bld\build.cmd -c %build_args%
cache:
  - C:\OpenSSL-Win32
matrix:
    fast_finish: true
